name: Compilar APK Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        working-directory: ./brickstock
        run: flutter pub get

      - name: Compilar APK
        working-directory: ./brickstock
        run: flutter build apk --release

      - name: Subir APK para descargar
        uses: actions/upload-artifact@v4
        with:
          name: brickstock-apk
          path: brickstock/build/app/outputs/flutter-apk/app-release.apk